version: '3.8'

services:
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "${VITE_FRONTEND_PORT}:${VITE_FRONTEND_PORT}"
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - my-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  test:
    build: ./backend
    command: npm run test:watch
    depends_on:
      - db
volumes:
  my-db-data:
